site_name: Hotmaps Wiki
site_url: https://danieldreke.github.io/github-wiki/
repo_url: https://github.com/danieldreke/github-wiki/wiki
edit_uri: ./_edit
# edit_link_title: Edit on GitHub
# edit_uri: ./{page.url.rstrip('/')}/_edit
#edit_uri: edit/{page.url.rstrip('/')}
# extra_javascript:
  # - fix-edit-on-github-links.js
#nav:
#  - Home: index.md
#  - About: about.md
plugins:
  - search
  # - git-revision-date-localized
  - mkdocs-video
  - i18n:
      # default_language: en
      # languages:
      #   - en: English
      #   - de: Deutsch
      #   - fr: Français
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
        - locale: fr
          name: Français
  # - i18n:
  #     # docs_structure: folder
  #     docs_structure: suffix      
  #     languages:
  #       - locale: en
  #         default: true
  #         name: English
  #         build: true
  #       - locale: fr
  #         name: Français
  #         build: true
theme:
  name: material
  language: en  # Set your default language
  locale: en
  # name: readthedocs
  features:
    - content.action.edit
  user_color_mode_toggle: true
  prev_next_buttons_location: none
  # logo: https://www.hotmaps-project.eu/wp-content/uploads/2017/03/logo_footer.svg
  logo: https://www.hotmaps-project.eu/wp-content/themes/JointsWP/assets/images/logo_menu.svg
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: light blue
    accent: deep purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: cyan
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to light mode
# docs_dir: wiki
hooks:
  - fix_edit_url.py
extra_css:
    - custom.css  
