site_name: Hotmaps Wiki
site_url: https://danieldreke.github.io/github-wiki/
repo_url: https://github.com/danieldreke/github-wiki/wiki

nav:
  - Wiki Introduction:
    - Welcome Page: index.md
  - Data Sets:
    - 'Hotmaps Data Set: Method Of Data Collection': 'Hotmaps-Data-Set:-Method-Of-Data-Collection.md'
    # - Hotmaps open data repositories: Hotmaps-open-data-repositories.md
  - 'General Tool Functionalities & Structure':
    - Introduction To User Interface: Introduction-To-User-Interface.md
  - For Authors:
    - How to Embed Videos: Embedded-Video-Examples.md

edit_uri: ./_edit
# docs_dir: wiki
hooks:
  - fix_edit_url.py
extra:
  generator: false
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/danieldreke/github-wiki/wiki
extra_css:
  - custom.css
markdown_extensions:
  - attr_list  # allows empty anchor links like [](){#top}
  - pymdownx.magiclink  # converts bare URLs into hyperlinks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  # - mkdocs-video
  - ezlinks  # allows [[Page Name]] links
  - i18n:
      # docs_structure: folder
      # docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch (Work in progress)
          build: true
  #       - locale: fr
  #         name: Français
theme:
  name: material
  # name: readthedocs
  language: en
  locale: en
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: https://wiki.hotmaps.hevs.ch/Home/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    # - navigation.instant  # make page behave like Single Page Application
    # - navigation.sections  # disable collapsing of sections
    - navigation.expand  # expand all collapsible subsections by default
    - navigation.top
    - navigation.path
    - navigation.footer
    # - navigation.tracking  # should add tracking but does not seem to work
    - content.code.copy  #
    # - search.highlight  # disabled as not known how user can toggle this feature
  user_color_mode_toggle: true
  # prev_next_buttons_location: none
  # logo: https://www.hotmaps-project.eu/wp-content/uploads/2017/03/logo_footer.svg
  logo: https://www.hotmaps-project.eu/wp-content/themes/JointsWP/assets/images/logo_menu.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: light blue
      primary: cyan
      accent: cyan
      # primary: #0AA7B8  # hotmaps cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
