site_name: Hotmaps Wiki
site_url: https://danieldreke.github.io/github-wiki/
repo_url: https://github.com/danieldreke/github-wiki/wiki
edit_uri: ./_edit
# docs_dir: wiki
hooks:
  - fix_edit_url.py
extra_css:
  - ./custom.css  
plugins:
  - search
  - mkdocs-video
  - i18n:
      # docs_structure: folder
      # docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
        - locale: fr
          name: Français
theme:
  name: material
  # name: readthedocs
  language: en
  locale: en
  features:
    - content.action.edit
  user_color_mode_toggle: true
  prev_next_buttons_location: none
  # logo: https://www.hotmaps-project.eu/wp-content/uploads/2017/03/logo_footer.svg
  logo: https://www.hotmaps-project.eu/wp-content/themes/JointsWP/assets/images/logo_menu.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: light blue
      primary: #0AA7B8
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: cyan
      primary: #0AA7B8
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
