site_name: GitHub Wiki to Github Pages via mkdocs and GitHub Actions
#nav:
#  - Home: index.md
#  - About: about.md
theme:
#  name: material
  name: readthedocs
  features:
    - content.action.edit
docs_dir: wiki
